# Generated by Django 3.0.6 on 2020-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200718_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='thumbnail',
            field=models.ImageField(default=1, editable=False, upload_to='avatar_thumbs'),
            preserve_default=False,
        ),
    ]
