# Generated by Django 3.0.6 on 2020-07-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200702_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[(5, 'Workday'), (7, 'Everyday'), (1, 'Holiday')], default=5, max_length=2),
        ),
    ]
