# Generated by Django 3.0.6 on 2020-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20200702_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='(automatic) created date'),
        ),
    ]
