# Generated by Django 3.0.6 on 2020-07-11 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_auto_20200711_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='date for the task_done_at'),
            preserve_default=False,
        ),
    ]
