# Generated by Django 3.0.6 on 2022-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_auto_20200719_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='done',
            field=models.DateTimeField(blank=True, help_text='date for the task_done_at', null=True),
        ),
    ]
